src/lib.rs

Without this change, num_cpus doesn't build when cross-compiling for iOS. (iOS provides the same sysconf interface as macos.)
I can't test the other BSDs affected by this change, but I'm pretty sure this is correct. The `not(unix)` that was present excluded all of those BSDs, as evidenced by `target_os = macos` showing up on two different implementations but not causing problems.

Fix cfg checks for iOS and other BSDs

---

src/lib.rs

r? @seanmonstar 
```
[larsberg@lbergstrom android-ndk-r9c]$ grep -r _SC_NPROCESSORS_ONLN *
platforms/android-18/arch-arm/usr/include/sys/sysconf.h:#define _SC_NPROCESSORS_ONLN            0x0061
platforms/android-18/arch-mips/usr/include/sys/sysconf.h:#define _SC_NPROCESSORS_ONLN            0x0061
```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/seanmonstar/num_cpus/9)

Add Android version of get_num_cpus

---

src/lib.rs

builded and tested under openbsd with rustc:
- 1.1.0 beta
- master
@seanmonstar : does the previous code have been tested under some BSD before ?
NOTE: the construct `*mut _ as *mut _` has been copied from `rustc/src/compiletest/raise_fd_limit.rs`

correct mismatched types on sysctl

---

Cargo.toml
src/lib.rs

This has a few changes:
* All BSD definitions are synced with libtest, relying on liblibc-defined constants
* The Android definition also now relies on a liblibc-defined constant
* The winapi/kernel32 deps were dropped as they take 30s to compile where this library takes 0.1s

Sync some definitions and boost compile times

---

src/lib.rs

Fixes #26 
I'm not sure if this is the best solution. JavaScript doesn't support threads natively, emscripten has only experimental support for threading via some kind of Firefox nightly extension. So AFAIK practically, threads are unusable right now.
So I see three possibilities:
1. Do what this PR does right now (return 1 CPU)
2. Panic in `get_num_cpus()` to signal that the operation doesn't make any sense in the current environment 
3. Don't do anything, because compiling this crate with said target doesn't make any sense
What do you think?

Add dummy implementation for emscripten targets

---

src/lib.rs

As some background, [Fuchsia](https://en.wikipedia.org/wiki/Google_Fuchsia) is a new operating system [under development](https://github.com/fuchsia-mirror) by Google. It is based on a new microkernel called [Magenta](https://github.com/fuchsia-mirror/magenta).
Used for `nproc` in coreutils.
ref https://github.com/uutils/coreutils/issues/999
cc @raphlinus

Add support for Fuchsia.

---

src/lib.rs

A proper implementation is missing, as support for Haiku in rust's
libc is incomplete.

Add initial Haiku support.

---

src/lib.rs

Count processors via affinity mask on linux

---

src/lib.rs

This pull request aims to close #34, which could result in an inexact number of CPUs on Android / ARM targets.

Use PROCESSORS_CONF instead of PROCESSORS_ONLN to fix ARM bug

---

.travis.yml

This commit modifies the Travis CI settings to also build and test the crate on Mac OS X targets.
Improves #47, although more improvemenets are required before the issue is closed (e.g. build the crate for Android).
The documentation for multi-OS builds is at https://docs.travis-ci.com/user/multi-os/

Add OS X environment for Travis CI

---

.travis.yml

This commit tries to improve #47. It adds support for building the following targets:
- Linux
- Mac OS X
- Android (x86 and ARM)
- iOS
- FreeBSD
and also runs tests on the first two.
The beta and nightly targets are only tested on Linux x64, as they were until now. All other OSes use stable Rust.
The commit also changed the `cache` option to `cache: cargo`, since that is the setting [recommended by Travis](https://docs.travis-ci.com/user/caching/#Rust-Cargo-cache) for Rust projects. It should do the same as the previous setting, and additionally cache the Cargo installation folder.
Also added the `dist: trusty` setting, to use the new [`trusty` images on Travis](https://docs.travis-ci.com/user/trusty-ci-environment/). They are faster, because they are container based.

Add more targets to CI

---

Cargo.toml
src/lib.rs

I had a pull request to fix #34. Unfortunately that broke Android builds. I've since submitted a pull request to `libc`, and it's now accepted and released.
This pull request changes `Cargo.toml` to use `libc` to version `0.2.26` or newer.
Fixes #34.
Also, issue #8 asks for Android support, and I think `num_cpus` had it for a while. It can be closed too.

Fix wrong number of CPUs on Android targets

---

.travis.yml
src/lib.rs

Travis CI [virtualizes its 16 physical CPUs to 2 per instance](https://docs.travis-ci.com/user/reference/overview/).
This PR:
* Fixes `test_physical_less_logical` by reversing the comparison (`logical >= physical` becomes `logical <= physical`) when the `TRAVIS` env var is present, which [it will be on Travis instances](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables). This reflects the reality that Travis's virtualization means there genuinely are fewer logical cores (2) than physical (16). Tests still pass locally and on AppVeyor because of the env var check.
* Adds a test that the number of logical cores is exactly 2 when the `TRAVIS` env var is present. I added this to prevent potential future regressions. In other systems (specifically Haskell) …

Add test for Travis CPU counts

---

src/lib.rs

Hope it is useful. Please read before you accept to make sure you're happy.

Add more documentation

---

src/lib.rs

Changes the spelling of "fallback" to "fall back".
Fixes #54.

Change `fallback` to `fall back`

---

src/lib.rs

This adds the *wasm-unknown-unknown* backend similar to the already present *wasm-unknown-emscripten*, i.e. a dummy function that just returns 1 as the number of CPUs. I thought it better to have a separate function for it, i.e. distinct from the emscripten one, but feel free to coalesce the two if needed be. I have prepared a test repo for it: [oldmammuth/test-num_cpus](https://github.com/oldmammuth/test-num_cpus).

added dummy wasm-unknown-unknown backend

---

src/lib.rs

The x86_64-fortanix-unknown-sgx recently gained Tier 3 support upstream.

Add support for x86_64-fortanix-unknown-sgx target 

---

src/lib.rs

As the commit suggests, this adds support for an illumos OS target.

Add illumos support

---

examples/values.rs
src/lib.rs

This also adds an example which prints both available values, to let the user test with a binary.
The binding has been generated manually from the C++ API, but its ABI is stable so this will never cause any issue.
Please make a 1.10.1 patch release afterwards, so that cargo can use it.

Actually add Haiku support

---

src/lib.rs

Bitrig is now defunct and rustc has already removed its support.

Remove bitrig support

---

Cargo.toml
src/lib.rs

We are developing the unikernel RustyHermit (https://github.com/hermitcore/libhermit-rs), where the kernel is written in Rust and is already part of the Rust Standard Library. With this pull request, we want to integrate our interface to determine the number of CPUs.

add support of the unikernel RustyHermit

---

src/lib.rs

It *probably* doesn't matter.  But really it can only help.  It's theoretically a performance malus but it's so tiny to be irrelevant; I have yet to need a program to find out how many CPU's it has more than once.
Safety: all the uses of `zeroed()` are for C structs that contain integers, raw pointers or `c_char` only, so it's always valid.
Edit: Hah, I didn't see #82.  Either one is good!

Replace `mem::uninitialized()` with `mem::zeroed()`

---

Cargo.toml

libc is already not used on windows, no need to download & compile it:
https://github.com/seanmonstar/num_cpus/blob/9b146faf097c6e2b0bb0a313d0a978e537eeb0fd/src/lib.rs#L34-L35
(**EDIT:** looks like this shaves a good 15 seconds off each appveyor build? [182](https://ci.appveyor.com/project/seanmonstar/num-cpus/builds/33789451) vs [185](https://ci.appveyor.com/project/seanmonstar/num-cpus/builds/35087680))

Cull unused libc dependency on windows

---

src/lib.rs

Document always returning at least 1 core

---

.github/workflows/ci.yml
fixtures/cgroups/proc/cgroups/mountinfo_multi_opt
fixtures/cgroups/proc/cgroups/mountinfo_zero_opt
src/linux.rs

There could be zero or more optional fields in mountinfo according to https://man7.org/linux/man-pages/man5/proc.5.html
And also there's some minor code cleanup.

fix(cgroup): fix parse zero or multi optional fields in mountinfo

---

src/linux.rs

Using this from Miri leads to the following error:
```
error: unsupported operation: `open` not available when isolation is enabled
--> /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/unix/fs.rs:887:36
|
887 |         let fd = cvt_r(|| unsafe { open64(path.as_ptr(), flags, opts.mode as c_int) })?;
|                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `open` not available when isolation is enabled
|
= help: pass the flag `-Zmiri-disable-isolation` to disable isolation;
= help: or pass `-Zmiri-isolation-error=warn` to configure Miri to return an error code from isolated operations (if supported for that operation) and continue with a warning
= note: inside closure at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/ …
```

do not attempt to open files in Miri

---

src/lib.rs

The physical CPU number detection is done by dividing logical CPU number with SMT mode.

Support AIX operating system
